trunk/CourseWork/ror/Assign4/library2/config/routes.rb
ActionController::Routing::Routes.draw do |map|
  map.resources :authors
  map.resources :publishers
  map.resources :books
  
  map.resources :books, :collection => { :search => [:post] }
  map.show_book 'books/:id/show_book', :controller => 'books', :action => 'show_book'
  map.show_books_of_author 'authors/:id/show_books_of_author', :controller => 'authors', :action => 'show_books_of_author'
  map.show_books_of_publisher 'publishers/:id/show_books_of_publisher', :controller => 'publishers', :action => 'show_books_of_publisher'
  map.edit_book_form 'books/:id/edit_book_form', :controller => 'books', :action => 'edit_book_form'
  map.create_new_form 'books/create_new_form', :controller => 'books', :action => 'create_new_form'
  map.edit_author_form 'authors/:id/edit_author_form', :controller => 'authors', :action => 'edit_author_form'
  map.clear_notifications 'library/clear_notifications', :controller => 'library', :action => 'clear_notifications'
  map.edit_publisher_form 'publishers/:id/edit_publisher_form', :controller => 'publishers', :action => 'edit_publisher_form'
  map.create_new_publisher_form 'publishers/create_new_publisher_form', :controller => 'publishers', :action => 'create_new_publisher_form'
  map.create_new_author_form 'authors/create_new_author_form', :controller => 'authors', :action => 'create_new_author_form'
  

  

  
  map.root :controller =>'library',:action => 'home'
end

trunk/CourseWork/ror/Assign4/library2/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :publisher
  has_and_belongs_to_many :authors
  validates_presence_of :authors , :message => ":You need atleast one Author"
  validates_presence_of :publisher , :message => ":You need atleast one Publisher"
  validates_associated :publisher
  validates_presence_of :title, :message => ":This field cannot be blank"
  validates_length_of :title, :maximum => 20, :message= => "title lenght can be upto 20"
end

trunk/CourseWork/ror/Assign4/library2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  def search
    search_string = params[:search][:query].strip
    @books=Book.find(:all,:conditions => 'title LIKE "%'+ search_string + '%"')
    flash[:notice] = 'Sorry No books found..'if (@books.size ==0 || @books == nil)
    render :partial => 'library/books', :locals => {:books => @books,:heading => "Search Result for '#{search_string}'" }
  end
  
  def show_book
    @book = Book.find(params[:id])
    render :partial => 'show', :locals => {:book => @book }
  end
  
  def create_new_form
    @book = Book.new
    render :partial => 'new', :locals => {:book => @book }
  end
  
  # GET /books/1/edit
  def edit_book_form
    @book = Book.find(params[:id])
    render :partial => 'new', :locals => {:book => @book, :heading => 'Edit Book' }
  end
  
  
  # POST /books
  # POST /books.xml
  def create
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        flash[:notice] = 'Book was successfully created.'
        format.html { render :partial => 'library/books', :locals => {:books => Book.all,:heading => "Books In Library" }}
      else
        format.html {render :partial => 'layouts/err', :locals => {:errors =>@book.errors } ,:status => 444}
      end
    end
  end
  
  # PUT /books/1
  # PUT /books/1.xml
  def update
    @book = Book.find(params[:id])
    
    respond_to do |format|
      if @book.update_attributes(params[:book])
        flash[:notice] = 'Book was successfully updated.'
        format.html { render :partial => 'library/books', :locals => {:books => Book.all,:heading => "Books In Library" }}
      else
        format.html {render :partial => 'layouts/err', :locals => {:errors =>@book.errors } ,:status => 444}
      end
    end
  end
  
  # DELETE /books/1
  # DELETE /books/1.xml
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = 'Book was successfully destroyed.'
    
    render :partial => 'library/books', :locals => {:books => Book.all,:heading => "Books In Library" }
  end
end

trunk/CourseWork/ror/Assign4/library2/app/helpers/books_helper.rb
module BooksHelper
end

trunk/CourseWork/ror/Assign4/library2/app/views/books/_new.html.erb
<div id = "error_book" align = "center"></div>

<h3>Create New Book</h3>
<% remote_form_for( book, :update => {:success =>'content' , :failure => "error_book"}) do |f| %>
	
	<%= f.error_messages %>

<table>  
  <tr> 
    <td><%= f.label :title %></td>
    <td><%= f.text_field :title %></td>
  </tr>
  
  <tr>
   <td> <%= f.label :publisher_id %></td>
   <td> <%= f.select :publisher_id, Publisher.all.map {|d| [d.name, d.id]} %></td>
  </tr>

  <tr>
   <td> <%= f.label :author_id %></td>
   <td> <%= f.collection_select(:author_ids, Author.all, :id, :first_name,{}, {:multiple => :multiple}) %></td>
   </tr>  
    
   <tr>
   	<td  align="center" ><%= f.submit 'Create' %></td>
	<td> <input type="button" value = "Done" onclick = "clearDiv('newbook')"></td>
	</tr>
	
</table>
  
<% end %>

trunk/CourseWork/ror/Assign4/library2/app/views/books/_show.html.erb
<p>
  <b>Title:</b>
  <%=h book.title %>
</p>

<p>
  <b>Publisher:</b>
  <%= book.publisher.name %>
</p>

<p>
  <b>Author(s):</b>
  <%=h book.authors.map {|auth| auth.display_name}.join(',')%></br>
</p>

<%= link_to 'Back', root_path %>

trunk/CourseWork/ror/Assign4/library2/app/views/books/_vasu.html.erb
Hello Vasu :)

trunk/CourseWork/ror/Assign4/library2/app/views/books/show.html.erb
<p>
  <b>Title:</b>
  <%=h @book.title %>
</p>

<p>
  <b>Publisher:</b>
  <%= @book.publisher.name %>
</p>

<p>
  <b>Author(s):</b>
  <%=h @book.authors.map {|auth| auth.display_name}.join(',')%></br>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', @book, :confirm => 'Are you sure?', :method => :delete %>|
<%= link_to 'Back', root_path %>